# Apply the settings in this .travis.yml to your own one.
# sudo: required
sudo: false
dist: trusty
language: generic
addons:
    apt:
        packages:
            - libunwind8
env:
    global:
        # Replace framework with core when you want to build a .NET Core project, not a .NET Framework project.
        - "TRAVIS_MSBUILD_MODE=framework"
        # The location of travis-msbuild. You probably need to change this for your project!
        - "TRAVIS_MSBUILD=$TRAVIS_BUILD_DIR"
        # - "TRAVIS_MSBUILD=$TRAVIS_BUILD_DIR/travis-msbuild"
        - "TRAVIS_MSBUILD_BIN=$TRAVIS_MSBUILD/bin"
        # Replace the following path with the path to a copy of the .NET Framework you're depending on, f.e. a pre-built copy of the Mono Framework API.
        - "TRAVIS_MSBUILD_FRAMEWORK=$TRAVIS_MSBUILD/lib-dotnet"
        - "PATH=$PATH:$TRAVIS_MSBUILD_BIN"
before_install:
    # When pushing from Windows, the bash scripts aren't marked executable.
    - chmod a+x "$TRAVIS_MSBUILD_BIN"/msbuild-prepare
    - msbuild-prepare
    # libicu52 and libunwind8 are pre-installed.
#script:
    # msbuild <pass MSBuild your parameters here as if it were xbuild>
    # or: msbuild-core
    # or: msbuild-framework
mono: none
dotnet: 2.0.0
script:
  - dotnet restore
  - dotnet build HelloWorld.sln
